@baseURL = http://localhost:3001/api

### create a post
POST {{baseURL}}/posts HTTP/1.1
Content-Type: application/json

{
    "content": "Hello world"
}

### get a post
GET {{baseURL}}/posts/465207 HTTP/1.1

### create comment
POST {{baseURL}}/comments/465207 HTTP/1.1
Content-Type: application/json

{
    "text": "great content"
}

### get a comment
GET {{baseURL}}/comments/701578 HTTP/1.1


### upload
POST {{baseURL}}/uploads HTTP/1.1


### upload images
POST {{baseURL}}/uploads/image HTTP/1.1

### get images
GET {{baseURL}}/uploads/image/65ea60d4b8c01b17a5a6b88a HTTP/1.1